name: GitHub Container Registry

on:
  push:
    tags:
      - '*'

jobs:
  ghcr:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/dify-unsandboxed-sandbox:${{ env.TAG }}
          push: true
